/**
 * 10+ Data-Driven Resume & Biodata Templates for ResumewithAI
 * Requirement #30 & #31: Completely data-driven, changing templates NEVER alters data.
 */

export const TEMPLATES = [
  {
    id: 'modern',
    name: 'Modern Clean',
    category: 'Popular',
    description: 'Clean, contemporary layout with warm accent tones, clear hierarchy, and balanced whitespace.',
    accentColor: '#F97316',
    font: 'Plus Jakarta Sans',
    layout: 'single',
    headerStyle: 'modern',
    tag: 'Recommended',
    previewBg: 'bg-white',
  },
  {
    id: 'classic',
    name: 'Classic Corporate',
    category: 'Traditional',
    description: 'Timeless traditional format trusted by Fortune 500 recruiters and enterprise hiring teams.',
    accentColor: '#171717',
    font: 'Inter',
    layout: 'single',
    headerStyle: 'centered',
    tag: 'ATS Optimized',
    previewBg: 'bg-neutral-50',
  },
  {
    id: 'minimal',
    name: 'Nordic Minimal',
    category: 'Minimal',
    description: 'Ultra-refined Scandinavian aesthetic with generous whitespace and elegant typography.',
    accentColor: '#525252',
    font: 'Inter',
    layout: 'single',
    headerStyle: 'left',
    tag: 'Clean',
    previewBg: 'bg-white',
  },
  {
    id: 'professional',
    name: 'Professional Slate',
    category: 'Corporate',
    description: 'Crisp, structured corporate layout with subtle left accent markers and structured grids.',
    accentColor: '#0284C7',
    font: 'Plus Jakarta Sans',
    layout: 'single',
    headerStyle: 'banner',
    tag: 'Corporate',
    previewBg: 'bg-slate-50',
  },
  {
    id: 'executive',
    name: 'Executive Leadership',
    category: 'Executive',
    description: 'Designed for VPs, directors, and senior leaders to showcase strategic impact and milestones.',
    accentColor: '#9A3412',
    font: 'Outfit',
    layout: 'single',
    headerStyle: 'executive',
    tag: 'Leadership',
    previewBg: 'bg-amber-50/30',
  },
  {
    id: 'creative',
    name: 'Creative Studio',
    category: 'Creative',
    description: 'Dynamic two-column layout ideal for UI/UX designers, creative directors, and innovators.',
    accentColor: '#F97316',
    font: 'Outfit',
    layout: 'two-column-left',
    headerStyle: 'creative',
    tag: 'Designer Pick',
    previewBg: 'bg-orange-50/40',
  },
  {
    id: 'ats_friendly',
    name: 'ATS Maximum',
    category: 'ATS Focused',
    description: 'Engineered specifically for 100% pass rates across Taleo, Workday, Greenhouse, and Lever.',
    accentColor: '#262626',
    font: 'Inter',
    layout: 'single',
    headerStyle: 'standard',
    tag: '99% ATS Match',
    previewBg: 'bg-white',
  },
  {
    id: 'developer',
    name: 'Dev Terminal',
    category: 'Tech & Engineering',
    description: 'Optimized for software developers with monospace accents, GitHub links, and tech stacks.',
    accentColor: '#EA580C',
    font: 'Plus Jakarta Sans',
    layout: 'two-column-right',
    headerStyle: 'dev',
    tag: 'For Engineers',
    previewBg: 'bg-zinc-50',
  },
  {
    id: 'student',
    name: 'Campus Fresher',
    category: 'Entry Level',
    description: 'Prioritizes education, academic projects, coursework, and extracurricular achievements.',
    accentColor: '#F97316',
    font: 'Inter',
    layout: 'single',
    headerStyle: 'student',
    tag: 'Freshers & Interns',
    previewBg: 'bg-orange-50/20',
  },
  {
    id: 'academic',
    name: 'Academic Curriculum Vitae',
    category: 'Academic & Medical',
    description: 'Comprehensive multi-section CV format for researchers, professors, and medical doctors.',
    accentColor: '#475569',
    font: 'Inter',
    layout: 'single',
    headerStyle: 'academic',
    tag: 'CV & Research',
    previewBg: 'bg-slate-50/40',
  },
  {
    id: 'biodata_modern',
    name: 'Modern Biodata',
    category: 'Biodata',
    description: 'Contemporary biodata format with clear personal, horoscope, family, and professional blocks.',
    accentColor: '#F97316',
    font: 'Outfit',
    layout: 'biodata',
    headerStyle: 'biodata',
    tag: 'Biodata Format',
    previewBg: 'bg-orange-50/30',
  },
  {
    id: 'biodata_traditional',
    name: 'Traditional Vedic Biodata',
    category: 'Biodata',
    description: 'Traditional marriage biodata with auspicious motifs, detailed astrological and family hierarchy.',
    accentColor: '#C2410C',
    font: 'Outfit',
    layout: 'biodata',
    headerStyle: 'traditional',
    tag: 'Marriage Biodata',
    previewBg: 'bg-amber-50/50',
  },
];

export const FONT_OPTIONS = [
  { id: 'Plus Jakarta Sans', label: 'Plus Jakarta Sans (Modern & Crisp)' },
  { id: 'Inter', label: 'Inter (Clean & Highly Readable)' },
  { id: 'Outfit', label: 'Outfit (Geometric & Expressive)' },
  { id: 'Playfair Display', label: 'Playfair Display (Editorial Serif)' },
  { id: 'Source Code Pro', label: 'Source Code Pro (Monospace Accents)' },
];

export const COLOR_PRESETS = [
  { id: '#F97316', label: 'Brand Orange', bg: 'bg-orange-500' },
  { id: '#EA580C', label: 'Deep Orange', bg: 'bg-orange-600' },
  { id: '#0284C7', label: 'Ocean Blue', bg: 'bg-sky-600' },
  { id: '#059669', label: 'Emerald Green', bg: 'bg-emerald-600' },
  { id: '#7C3AED', label: 'Royal Purple', bg: 'bg-violet-600' },
  { id: '#E11D48', label: 'Crimson Rose', bg: 'bg-rose-600' },
  { id: '#171717', label: 'Charcoal Dark', bg: 'bg-neutral-900' },
  { id: '#475569', label: 'Slate Navy', bg: 'bg-slate-600' },
];
